services:
  prometheus:
    container_name: PROMETHUES
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-config:/etc/prometheus
    networks:
      - monitoring

  grafana:
    container_name: GRAFANA
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring
    secrets:
      - grafana_admin_password
    environment:
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
  
  mssql-server:
    user: root
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MSSQL-SERVER
    platform: linux/amd64
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD_FILE=/run/secrets/mssql_sa_password
    ports:
      - "1433:1433"
    networks:
      - monitoring
    volumes:
      - mssql_data:/var/opt/mssql/data
    secrets:
      - mssql_sa_password  


  mssql_exporter:
    container_name: MSSQL_EXPORTER
    image: "danieloliver/mssql_exporter:latest"
    ports:
      - "9100:9100"
    depends_on:
      - mssql-server
    environment:
      - PROMETHEUS_MSSQL_DataSource=Server=tcp:mssql-server,1433;Initial Catalog=master;Persist Security Info=False;User ID=sa;Password=Zxcvb@123;MultipleActiveResultSets=False;Encrypt=False;TrustServerCertificate=True;Connection Timeout=10;
      - PROMETHEUS_MSSQL_ConfigFile=metrics.json
      - PROMETHEUS_MSSQL_ServerPath=metrics
      - PROMETHEUS_MSSQL_ServerPort=9100
      - PROMETHEUS_MSSQL_AddExporterMetrics=false
      - PROMETHEUS_MSSQL_Serilog__MinimumLevel=Information
      - |
        PROMETHEUS_MSSQL_ConfigText=
        {
          "Queries": [
            {
              "Name": "mssql_process_status",
              "Query": "SELECT status, COUNT(*) count FROM sys.sysprocesses GROUP BY status",
              "Description": "Counts the number of processes per status",
              "Usage": "GaugesWithLabels",
              "Columns": [
                {
                  "Name": "status",
                  "Label": "status",
                  "Usage": "GaugeLabel",
                  "Order": 0
                },
                {
                  "Name": "count",
                  "Label": "count",
                  "Usage": "Gauge"
                }
              ]
            },
            {
              "Name": "mssql_process_connections",
              "Query": "SELECT ISNULL(DB_NAME(dbid), 'other') as dbname, COUNT(dbid) as connections FROM sys.sysprocesses WHERE dbid > 0 GROUP BY dbid",
              "Description": "Counts the number of connections per db",
              "Usage": "GaugesWithLabels",
              "Columns": [
                {
                  "Name": "dbname",
                  "Label": "dbname",
                  "Usage": "GaugeLabel",
                  "Order": 0
                },
                {
                  "Name": "connections",
                  "Label": "count",
                  "Usage": "Gauge"
                }
              ]
            },
            {
              "Name": "mssql_deadlocks",
              "Query": "SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Number of Deadlocks/sec' AND instance_name = '_Total'",
              "Description": "Number of lock requests per second that resulted in a deadlock since last restart",
              "Columns": [
                {
                  "Name": "cntr_value",
                  "Label": "mssql_deadlocks",
                  "Usage": "Gauge",
                  "DefaultValue": 0
                }
              ]
            },
            {
              "Name": "mssql_cache_hit_ratio",
              "Query": "SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Buffer cache hit ratio'",
              "Description": "Buffer cache hit ratio",
              "Columns": [
                {
                  "Name": "cntr_value",
                  "Label": "buffer_cache_hit_ratio",
                  "Usage": "Gauge",
                  "DefaultValue": 0
                }
              ]
            },
            {
              "Name": "mssql_page_life_expectancy",
              "Query": "SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Page life expectancy'",
              "Description": "Page life expectancy",
              "Columns": [
                {
                  "Name": "cntr_value",
                  "Label": "page_life_expectancy",
                  "Usage": "Gauge",
                  "DefaultValue": 0
                }
              ]
            },
            {
              "Name": "mssql_cpu_usage",
              "Query": "SELECT record_id, event_time, SQLProcessUtilization, SystemIdle, 100 - SystemIdle - SQLProcessUtilization AS OtherProcessUtilization FROM sys.dm_os_ring_buffers WHERE ring_buffer_type = N'RING_BUFFER_SCHEDULER_MONITOR' AND record_id = (SELECT MAX(record_id) FROM sys.dm_os_ring_buffers WHERE ring_buffer_type = N'RING_BUFFER_SCHEDULER_MONITOR')",
              "Description": "CPU usage of SQL Server",
              "Columns": [
                {
                  "Name": "SQLProcessUtilization",
                  "Label": "sql_process_utilization",
                  "Usage": "Gauge",
                  "DefaultValue": 0
                },
                {
                  "Name": "SystemIdle",
                  "Label": "system_idle",
                  "Usage": "Gauge",
                  "DefaultValue": 0
                },
                {
                  "Name": "OtherProcessUtilization",
                  "Label": "other_process_utilization",
                  "Usage": "Gauge",
                  "DefaultValue": 0
                }
              ]
            },
            {
              "Name": "mssql_memory_usage",
              "Query": "SELECT cntr_value FROM sys.dm_os_performance_counters WHERE counter_name = 'Total Server Memory (KB)'",
              "Description": "Total memory used by SQL Server",
              "Columns": [
                {
                  "Name": "cntr_value",
                  "Label": "total_server_memory_kb",
                  "Usage": "Gauge",
                  "DefaultValue": 0
                }
              ]
            },
            {
              "Name": "mssql_io_stall",
              "Query": "SELECT database_id, file_id, io_stall_read_ms, io_stall_write_ms, io_stall_total_ms, num_of_reads, num_of_writes, num_of_bytes_read, num_of_bytes_written FROM sys.dm_io_virtual_file_stats(NULL, NULL)",
              "Description": "I/O stall statistics",
              "Usage": "GaugesWithLabels",
              "Columns": [
                {
                  "Name": "database_id",
                  "Label": "database_id",
                  "Usage": "GaugeLabel",
                  "Order": 0
                },
                {
                  "Name": "file_id",
                  "Label": "file_id",
                  "Usage": "GaugeLabel",
                  "Order": 1
                },
                {
                  "Name": "io_stall_read_ms",
                  "Label": "io_stall_read_ms",
                  "Usage": "Gauge"
                },
                {
                  "Name": "io_stall_write_ms",
                  "Label": "io_stall_write_ms",
                  "Usage": "Gauge"
                },
                {
                  "Name": "io_stall_total_ms",
                  "Label": "io_stall_total_ms",
                  "Usage": "Gauge"
                },
                {
                  "Name": "num_of_reads",
                  "Label": "num_of_reads",
                  "Usage": "Gauge"
                },
                {
                  "Name": "num_of_writes",
                  "Label": "num_of_writes",
                  "Usage": "Gauge"
                },
                {
                  "Name": "num_of_bytes_read",
                  "Label": "num_of_bytes_read",
                  "Usage": "Gauge"
                },
                {
                  "Name": "num_of_bytes_written",
                  "Label": "num_of_bytes_written",
                  "Usage": "Gauge"
                }
              ]
            }
          ],
          "MillisecondTimeout": 4000
        }

    networks:
      - monitoring
    


volumes:
  prometheus-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./prom-data/
  grafana-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./grafana-data/
  mssql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./mssql_data/

networks:
  monitoring:
    driver: bridge

secrets:
  grafana_admin_password:
    file: ./grafana_admin_password.txt
  # db_user:
  #   file: ./db_user.txt
  # db_password:
  #   file: ./db_password.txt
  mssql_sa_password:
    file: ./mssql_sa_password.txt